import { getCurrentCompany } from "@/lib/session";
import prisma from "@/lib/prisma";
import QuotesClient from "./QuotesClient";

export default async function QuotesListPage() {
  const company = await getCurrentCompany();

  const quotes = await prisma.quoteRequest.findMany({
    where: { companyId: company.id },
    orderBy: { createdAt: "desc" },
  });

  return (
    <div className="p-4 lg:p-10 max-w-7xl mx-auto space-y-6 sm:space-y-8">
      <div className="space-y-1">
        <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">Quote Management</h1>
        <p className="text-slate-500 font-medium text-sm sm:text-base">Track and manage every delivery lead generated by your Qalt widget.</p>
      </div>
      <QuotesClient quotes={quotes} />
    </div>
  );
}
