import { getCurrentCompany } from "@/lib/session";
import prisma from "@/lib/prisma";
import {
  FileText,
  MapPin,
  Mail,
  Phone,
  Calendar,
  ExternalLink,
  ChevronRight
} from "lucide-react";
import Link from "next/link";

export default async function QuotesListPage() {
  const company = await getCurrentCompany();

  const quotes = await prisma.quoteRequest.findMany({
    where: { companyId: company.id },
    orderBy: { createdAt: "desc" },
  });

  return (
    <div className="p-4 lg:p-10 max-w-7xl mx-auto space-y-6 sm:space-y-8">
      {/* Header */}
      <div className="space-y-1">
        <h1 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">Quote Management</h1>
        <p className="text-slate-500 font-medium text-sm sm:text-base">Track and manage every delivery lead generated by your Qalt widget.</p>
      </div>

      {quotes.length === 0 ? (
        <div className="bg-white rounded-4xl border border-slate-200/60 shadow-2xl shadow-slate-200/50 overflow-hidden p-12 text-center">
          <div className="flex flex-col items-center">
            <div className="p-6 bg-slate-50 rounded-full text-slate-300 mb-4">
              <FileText size={48} />
            </div>
            <p className="text-slate-900 font-black text-xl mb-1">No leads found</p>
            <p className="text-slate-400 font-medium mb-6">Your quote history will appear here once customers interact with your widget.</p>
            <Link
              href="/dashboard/embed"
              className="px-6 py-3 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-100"
            >
              Setup Widget &rarr;
            </Link>
          </div>
        </div>
      ) : (
        <>
          {/* Desktop Table — hidden on mobile */}
          <div className="hidden md:block bg-white rounded-4xl border border-slate-200/60 shadow-2xl shadow-slate-200/50 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full border-collapse text-left min-w-[800px]">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-100">
                    <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Customer &amp; Date</th>
                    <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Route Details</th>
                    <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">Value</th>
                    <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Contact Information</th>
                    <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {quotes.map((quote) => (
                    <tr key={quote.id} className="group hover:bg-slate-50/80 transition-all duration-300">
                      <td className="px-8 py-6">
                        <div className="flex items-center gap-4">
                          <div className="h-10 w-10 rounded-xl bg-slate-900 flex items-center justify-center text-white font-black text-xs shrink-0">
                            {quote.customerName.charAt(0).toUpperCase()}
                          </div>
                          <div>
                            <p className="text-sm font-black text-slate-900 tracking-tight leading-none mb-1.5 group-hover:text-blue-600 transition-colors">
                              {quote.customerName}
                            </p>
                            <div className="flex items-center gap-2 text-[10px] font-black text-slate-400 uppercase tracking-tighter">
                              <Calendar size={10} />
                              {new Date(quote.createdAt).toLocaleDateString()}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-8 py-6">
                        <div className="space-y-2">
                          <div className="flex items-center gap-2 text-sm font-bold text-slate-700">
                            <MapPin size={12} className="text-blue-500" />
                            <span>{quote.pickupZip}</span>
                            <ChevronRight size={10} className="text-slate-300" />
                            <span>{quote.dropoffZip}</span>
                          </div>
                          <div className="flex items-center gap-3 text-xs text-slate-400 font-bold">
                            <span className="px-2 py-0.5 bg-slate-100 rounded text-slate-600">{quote.serviceType}</span>
                            <span>{quote.distanceMiles.toFixed(1)} miles</span>
                          </div>
                        </div>
                      </td>
                      <td className="px-8 py-6 text-center">
                        <div className="inline-flex flex-col">
                          <span className="text-lg font-black text-slate-900 tracking-tighter">${quote.estimatedPrice.toFixed(2)}</span>
                          <span className="text-[10px] font-black text-emerald-600 uppercase tracking-widest mt-0.5">ESTIMATED</span>
                        </div>
                      </td>
                      <td className="px-8 py-6">
                        <div className="space-y-1.5">
                          <div className="flex items-center gap-2 text-xs font-bold text-slate-600">
                            <Mail size={12} className="text-slate-300" />
                            {quote.customerEmail}
                          </div>
                          <div className="flex items-center gap-2 text-xs font-bold text-slate-600">
                            <Phone size={12} className="text-slate-300" />
                            {quote.customerPhone || "No phone provided"}
                          </div>
                        </div>
                      </td>
                      <td className="px-8 py-6 text-right">
                        <button className="inline-flex items-center justify-center h-10 w-10 rounded-xl bg-slate-100 text-slate-500 hover:bg-slate-900 hover:text-white transition-all shadow-sm">
                          <ExternalLink size={16} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Mobile Cards — shown only on mobile */}
          <div className="md:hidden space-y-3">
            {quotes.map((quote) => (
              <div key={quote.id} className="bg-white rounded-2xl border border-slate-200/60 shadow-sm p-5">
                <div className="flex items-start justify-between gap-3 mb-4">
                  <div className="flex items-center gap-3">
                    <div className="h-10 w-10 rounded-xl bg-slate-900 flex items-center justify-center text-white font-black text-xs shrink-0">
                      {quote.customerName.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <p className="text-sm font-black text-slate-900 tracking-tight leading-none mb-1">
                        {quote.customerName}
                      </p>
                      <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-400 uppercase tracking-tighter">
                        <Calendar size={9} />
                        {new Date(quote.createdAt).toLocaleDateString()}
                      </div>
                    </div>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="text-lg font-black text-slate-900 tracking-tighter leading-none">${quote.estimatedPrice.toFixed(2)}</p>
                    <p className="text-[10px] font-black text-emerald-600 uppercase tracking-widest mt-0.5">estimated</p>
                  </div>
                </div>

                <div className="flex items-center gap-2 text-sm font-bold text-slate-700 mb-2">
                  <MapPin size={12} className="text-blue-500 shrink-0" />
                  <span>{quote.pickupZip}</span>
                  <ChevronRight size={10} className="text-slate-300" />
                  <span>{quote.dropoffZip}</span>
                  <span className="ml-auto text-xs text-slate-400 font-bold">{quote.distanceMiles.toFixed(1)} mi</span>
                </div>

                <div className="border-t border-slate-100 pt-3 mt-3 space-y-1.5">
                  <div className="flex items-center gap-2 text-xs font-bold text-slate-500">
                    <Mail size={11} className="text-slate-300 shrink-0" />
                    <span className="truncate">{quote.customerEmail}</span>
                  </div>
                  {quote.customerPhone && (
                    <div className="flex items-center gap-2 text-xs font-bold text-slate-500">
                      <Phone size={11} className="text-slate-300 shrink-0" />
                      {quote.customerPhone}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
