"use client";

import { useEffect, useRef, useState } from "react";
import Image from "next/image";
import Script from "next/script";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";
import { ArrowRight, Loader2, Lock, Mail, ShieldCheck, Sparkles } from "lucide-react";
import QuoteWidgetForm from "@/components/widget/QuoteWidgetForm";

const TURNSTILE_SITE_KEY = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
const UNLOCK_KEY = "qalt_demo_unlocked";

const INPUT =
  "w-full px-4 py-3 bg-white border border-slate-200 rounded-xl text-[15px] font-medium text-slate-900 placeholder:text-slate-400 focus:border-red-500 focus:ring-2 focus:ring-red-500/20 outline-none transition-all";
const LABEL = "block text-[13px] font-bold text-slate-700 mb-1.5";

declare global {
  interface Window {
    turnstile?: {
      render: (el: HTMLElement, opts: Record<string, unknown>) => string;
      reset: (widgetId?: string) => void;
      remove: (widgetId?: string) => void;
    };
  }
}

// The interactive Northline widget mounts (and only then loads Google Maps /
// address services) after a visitor completes this gate. Before unlock we show
// a static, non-interactive preview image blurred behind the access form, so
// no Maps/API usage is generated by bots or casual traffic.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function GatedDemo({ company }: { company: any }) {
  const reduce = useReducedMotion();
  const [unlocked, setUnlocked] = useState(false);
  const [justUnlocked, setJustUnlocked] = useState(false);
  const [status, setStatus] = useState<"idle" | "submitting">("idle");
  const [error, setError] = useState("");
  const [token, setToken] = useState("");
  const turnstileBoxRef = useRef<HTMLDivElement>(null);
  const widgetIdRef = useRef<string | null>(null);

  // Restore access for the current browser session only. Deferred out of the
  // effect body (rAF) so we never set state synchronously during hydration.
  useEffect(() => {
    let ok = false;
    try {
      ok = sessionStorage.getItem(UNLOCK_KEY) === "1";
    } catch {
      /* sessionStorage unavailable — stay gated */
    }
    if (!ok) return;
    const id = requestAnimationFrame(() => setUnlocked(true));
    return () => cancelAnimationFrame(id);
  }, []);

  // Render Turnstile explicitly once the script is ready. Auto-rendering via the
  // `cf-turnstile` class races with React hydration and often leaves the widget
  // unmounted (no iframe, no token), which silently blocks the form. Explicit
  // render into our ref is deterministic and gives us the token via callback.
  useEffect(() => {
    if (!TURNSTILE_SITE_KEY) return;
    let cancelled = false;
    const render = () => {
      if (cancelled) return;
      const box = turnstileBoxRef.current;
      if (window.turnstile && box && widgetIdRef.current === null) {
        widgetIdRef.current = window.turnstile.render(box, {
          sitekey: TURNSTILE_SITE_KEY,
          theme: "light",
          callback: (t: string) => setToken(t),
          "error-callback": () => setToken(""),
          "expired-callback": () => setToken(""),
        });
      } else if (!window.turnstile || !box) {
        setTimeout(render, 200);
      }
    };
    render();
    return () => { cancelled = true; };
  }, [unlocked]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const companyName = (fd.get("companyName") as string)?.trim();
    const contactName = (fd.get("contactName") as string)?.trim();
    const email = (fd.get("email") as string)?.trim();
    const website = (fd.get("website") as string)?.trim();
    const honeypot = (fd.get("company_fax") as string) || "";

    if (!companyName || !contactName || !email) {
      setError("Please fill in your company, name, and work email.");
      return;
    }
    if (TURNSTILE_SITE_KEY && !token) {
      setError('Please complete the "I am human" check below.');
      return;
    }

    setStatus("submitting");
    setError("");
    try {
      const res = await fetch("/api/demo-access", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ companyName, contactName, email, website, honeypot, turnstileToken: token }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok && data?.success) {
        try {
          sessionStorage.setItem(UNLOCK_KEY, "1");
        } catch {
          /* ignore */
        }
        setJustUnlocked(true);
        setUnlocked(true);
        setStatus("idle");
      } else {
        setStatus("idle");
        setError(data?.error || "Something went wrong. Please try again.");
        setToken("");
        window.turnstile?.reset(widgetIdRef.current ?? undefined);
      }
    } catch {
      setStatus("idle");
      setError("Something went wrong. Please try again.");
      setToken("");
      window.turnstile?.reset(widgetIdRef.current ?? undefined);
    }
  };

  if (unlocked) {
    return (
      <div className="relative bg-slate-100 px-4 py-8 sm:px-8 sm:py-12 lg:px-14 lg:py-16 flex justify-center">
        <AnimatePresence>
          {justUnlocked && (
            <motion.div
              initial={reduce ? { opacity: 0 } : { opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
              onAnimationComplete={() => setTimeout(() => setJustUnlocked(false), 2600)}
              className="absolute top-4 z-20 inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-600 text-white text-xs font-black shadow-lg shadow-emerald-900/20"
            >
              <Sparkles size={13} /> Demo unlocked
            </motion.div>
          )}
        </AnimatePresence>
        <motion.div
          initial={reduce ? { opacity: 0 } : { opacity: 0, scale: 0.985 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
          className="w-full flex justify-center"
        >
          {/* eslint-disable-next-line @typescript-eslint/no-explicit-any */}
          <QuoteWidgetForm company={company as any} demoMode />
        </motion.div>
      </div>
    );
  }

  return (
    <div className="relative bg-slate-100 min-h-[560px] sm:min-h-[640px] flex items-center justify-center px-4 py-12 sm:px-8">
      {/* Static, non-interactive preview — no widget mounted, no Maps loaded */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none select-none" aria-hidden>
        <Image
          src="/images/demo-preview.png"
          alt=""
          fill
          priority
          className="object-cover object-top blur-[7px] scale-[1.06]"
        />
        <div className="absolute inset-0 bg-gradient-to-b from-white/70 via-white/65 to-white/85" />
      </div>

      {/* Access form */}
      <div className="relative z-10 w-full max-w-md">
        <div className="rounded-3xl border border-slate-200 bg-white/95 backdrop-blur-sm shadow-[0_30px_80px_-25px_rgba(0,0,0,0.35)] p-6 sm:p-8">
          <div className="flex items-center gap-2.5 mb-5">
            <div className="w-10 h-10 rounded-2xl bg-red-50 text-red-600 flex items-center justify-center shrink-0">
              <Lock size={18} />
            </div>
            <div>
              <h3 className="text-xl font-black text-slate-900 tracking-tight leading-tight">Try the Live Demo</h3>
              <p className="text-[13px] text-slate-500 font-medium leading-snug">
                Tell us about your delivery business to access the interactive Qalt demo.
              </p>
            </div>
          </div>

          <form onSubmit={handleSubmit} className="space-y-3.5">
            <div>
              <label htmlFor="g-companyName" className={LABEL}>Company name</label>
              <input id="g-companyName" name="companyName" required placeholder="Northline Delivery Co." className={INPUT} />
            </div>
            <div>
              <label htmlFor="g-contactName" className={LABEL}>Contact name</label>
              <input id="g-contactName" name="contactName" required placeholder="Jordan Reyes" className={INPUT} />
            </div>
            <div>
              <label htmlFor="g-email" className={LABEL}>Work email</label>
              <input id="g-email" name="email" type="email" required placeholder="you@company.com" className={INPUT} />
            </div>
            <div>
              <label htmlFor="g-website" className={LABEL}>Website</label>
              <input id="g-website" name="website" placeholder="yourdeliverycompany.com" className={INPUT} />
            </div>

            {/* Honeypot — hidden from humans, tempting to bots. Must stay empty. */}
            <div className="absolute -left-[9999px] top-0 h-0 w-0 overflow-hidden" aria-hidden>
              <label htmlFor="company_fax">Do not fill this field</label>
              <input id="company_fax" name="company_fax" type="text" tabIndex={-1} autoComplete="off" />
            </div>

            {TURNSTILE_SITE_KEY && (
              <>
                <Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" strategy="afterInteractive" />
                <div ref={turnstileBoxRef} className="flex justify-center pt-1" />
              </>
            )}

            {error && (
              <p className="text-sm font-semibold text-red-600 bg-red-50 border border-red-100 rounded-xl px-4 py-3">{error}</p>
            )}

            <button
              type="submit"
              disabled={status === "submitting"}
              className="group/btn w-full px-6 py-3.5 bg-red-600 text-white font-black rounded-none flex items-center justify-center gap-3 hover:bg-red-500 transition-all active:scale-[0.99] disabled:opacity-60 shadow-xl shadow-red-900/20 text-sm tracking-wide"
            >
              {status === "submitting" ? (
                <><Loader2 size={16} className="animate-spin" /> Verifying…</>
              ) : (
                <>Request Live Demo <ArrowRight size={16} className="group-hover/btn:translate-x-1.5 transition-transform" /></>
              )}
            </button>

            <div className="flex items-center justify-center gap-1.5 pt-1 text-[11px] font-semibold text-slate-400">
              <ShieldCheck size={13} className="text-emerald-500" /> Human-verified access. No payment required.
            </div>
            <p className="text-center text-[12px] font-medium text-slate-400 pt-1">
              Prefer email?{" "}
              <a href="mailto:business@qalt.site" className="inline-flex items-center gap-1 text-red-600 font-bold hover:text-red-500 transition-colors">
                <Mail size={12} /> business@qalt.site
              </a>
            </p>
          </form>
        </div>
      </div>
    </div>
  );
}
