import { revalidatePath } from "next/cache";
import { getCurrentCompany } from "@/lib/session";
import prisma from "@/lib/prisma";

const templates = {
  LOCAL_COURIER: { name:"Local Courier", description:"Simple local same-day pricing with a practical minimum.", baseRatePerMile:2.75, minimumCharge:45, useMinimumCharge:true, minMilesThreshold:0, weightFee:0, itemCountFee:0, stairsFee:15, insideDeliveryFee:20, addon3Fee:0, afterHoursFee:35, largeItemFee:0 },
  FINAL_MILE: { name:"Final Mile", description:"Higher-touch final-mile work with item and access charges.", baseRatePerMile:3.25, minimumCharge:65, useMinimumCharge:true, minMilesThreshold:0, weightFee:0.05, itemCountFee:3, stairsFee:20, insideDeliveryFee:35, addon3Fee:0, afterHoursFee:45, largeItemFee:35 },
  FURNITURE: { name:"Furniture Delivery", description:"Built for bulky items, stairs, and inside delivery.", baseRatePerMile:3.5, minimumCharge:85, useMinimumCharge:true, minMilesThreshold:0, weightFee:0.08, itemCountFee:5, stairsFee:25, insideDeliveryFee:45, addon3Fee:0, afterHoursFee:50, largeItemFee:55 },
  MEDICAL: { name:"Medical Equipment", description:"Scheduled equipment delivery with controlled access surcharges.", baseRatePerMile:3.0, minimumCharge:70, useMinimumCharge:true, minMilesThreshold:0, weightFee:0.04, itemCountFee:2, stairsFee:20, insideDeliveryFee:30, addon3Fee:0, afterHoursFee:55, largeItemFee:25 },
} as const;

export default async function PricingTemplatesPage() {
  const company = await getCurrentCompany();
  async function apply(formData: FormData) { "use server"; const company=await getCurrentCompany(); const key=String(formData.get("template")) as keyof typeof templates; const t=templates[key]; if(!t) return; const {name:_,description:__,...fields}=t; const existing=await prisma.pricingProfile.findFirst({where:{companyId:company.id,widgetSettingsId:null}}); if(existing) await prisma.pricingProfile.update({where:{id:existing.id},data:fields}); else await prisma.pricingProfile.create({data:{companyId:company.id,...fields}}); revalidatePath("/dashboard/pricing/templates"); revalidatePath("/dashboard/pricing"); }
  const profile=await prisma.pricingProfile.findFirst({where:{companyId:company.id,widgetSettingsId:null}});
  return <div className="mx-auto max-w-6xl space-y-6 p-4 lg:p-10"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-red-600">Phase 34</p><h1 className="mt-1 text-3xl font-black text-slate-950 dark:text-white">Pricing Templates</h1><p className="mt-2 text-sm font-medium text-slate-500">Start from a proven structure, then fine-tune it in Pricing Settings. Applying a template replaces the default profile values.</p></div><div className="rounded-2xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800">Current default: ${profile?.baseRatePerMile?.toFixed(2) ?? "2.50"}/mi · minimum ${profile?.minimumCharge?.toFixed(0) ?? "35"}</div><div className="grid gap-4 md:grid-cols-2">{Object.entries(templates).map(([key,t])=><form action={apply} key={key} className="rounded-3xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-[#111]"><input type="hidden" name="template" value={key}/><h2 className="text-xl font-black text-slate-950 dark:text-white">{t.name}</h2><p className="mt-2 text-sm font-medium leading-6 text-slate-500">{t.description}</p><div className="mt-5 flex gap-4 text-sm font-black text-slate-700 dark:text-zinc-300"><span>${t.baseRatePerMile.toFixed(2)}/mi</span><span>${t.minimumCharge} minimum</span></div><button className="mt-5 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-black text-white">Apply template</button></form>)}</div></div>;
}
