ALTER TABLE "Company"
ADD COLUMN IF NOT EXISTS "businessType" TEXT,
ADD COLUMN IF NOT EXISTS "onboardingStep" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "onboardingCompletedAt" TIMESTAMP(3);
