import { revalidatePath } from "next/cache";
import { getCurrentCompany } from "@/lib/session";
import prisma from "@/lib/prisma";
import { ensureBookingForQuote, listBookings, updateBooking } from "@/lib/growth-engine";

function localInput(date: Date | null) { if (!date) return ""; const d = new Date(date); const pad=(n:number)=>String(n).padStart(2,"0"); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }

export default async function BookingsPage() {
  const company = await getCurrentCompany();
  const accepted = await prisma.quoteRequest.findMany({ where: { companyId: company.id, deletedAt: null, OR: [{ status: { in: ["CONFIRMED","WON","PAID"] } }, { paymentStatus: "PAID" }] }, select: { id: true } });
  await Promise.all(accepted.map((q)=>ensureBookingForQuote(company.id,q.id)));
  const bookings = await listBookings(company.id);
  async function save(formData: FormData) { "use server"; const company = await getCurrentCompany(); const rawDate=String(formData.get("scheduledDate")||""); await updateBooking(company.id,{ id:String(formData.get("id")), scheduledDate:rawDate?new Date(rawDate):null, driverName:String(formData.get("driverName")||""), vehicle:String(formData.get("vehicle")||""), notes:String(formData.get("notes")||""), status:String(formData.get("status")||"UNSCHEDULED") }); revalidatePath("/dashboard/ops/bookings"); }
  return <div className="mx-auto max-w-7xl space-y-6 p-4 lg:p-10"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-red-600">Phase 32</p><h1 className="mt-1 text-3xl font-black text-slate-950 dark:text-white">Booking Workflow</h1><p className="mt-2 text-sm font-medium text-slate-500">Accepted and paid quotes become operational bookings automatically.</p></div>{bookings.length===0?<div className="rounded-3xl border border-dashed border-slate-300 p-10 text-center text-sm font-bold text-slate-500">No accepted bookings yet.</div>:<div className="grid gap-4">{bookings.map((b)=><form action={save} key={b.id} className="rounded-3xl border border-slate-200 bg-white p-6 dark:border-white/10 dark:bg-[#111]"><input type="hidden" name="id" value={b.id}/><div className="grid gap-4 lg:grid-cols-6"><div className="lg:col-span-2"><div className="text-lg font-black text-slate-950 dark:text-white">{b.customerName || b.customerEmail || "Customer"}</div><div className="mt-1 text-xs font-bold text-slate-400">${Number(b.estimatedPrice||0).toFixed(2)} · Quote {b.quoteRequestId.slice(-7)}</div></div><input name="scheduledDate" type="datetime-local" defaultValue={localInput(b.scheduledDate)} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/><input name="driverName" placeholder="Driver" defaultValue={b.driverName||""} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/><input name="vehicle" placeholder="Vehicle" defaultValue={b.vehicle||""} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/><select name="status" defaultValue={b.status} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"><option>UNSCHEDULED</option><option>SCHEDULED</option><option>ASSIGNED</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>CANCELLED</option></select></div><div className="mt-4 flex gap-3"><input name="notes" placeholder="Internal booking notes" defaultValue={b.notes||""} className="min-w-0 flex-1 rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/><button className="rounded-xl bg-slate-950 px-5 py-2 text-sm font-black text-white">Save booking</button></div></form>)}</div>}</div>;
}
