import Link from "next/link";
import { getCurrentCompany } from "@/lib/session";
import prisma from "@/lib/prisma";
import { estimatePriceDetailed, type EstimateRules } from "@/lib/calculator";
import { applyPricingRules } from "@/lib/growth-engine";

export default async function PricingSimulatorPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const company = await getCurrentCompany();
  const p = await searchParams;
  const distance=Math.max(0,Number(p.distance||10)); const weight=Math.max(0,Number(p.weight||0)); const items=Math.max(0,Number(p.items||1)); const stairs=Math.max(0,Number(p.stairs||0));
  const profile = await prisma.pricingProfile.findFirst({ where: { companyId: company.id, widgetSettingsId: null } });
  if (!profile) return <div className="p-10">Configure pricing first.</div>;
  const detailed=estimatePriceDetailed(distance,profile as unknown as EstimateRules,{ hasStairs:stairs>0,stairsFlights:stairs,needsInsideDelivery:false,needsAddon3:false,packageWeight:weight,itemCount:items });
  const rules=await applyPricingRules(company.id,distance,{ hasStairs:stairs>0,stairsFlights:stairs,needsInsideDelivery:false,needsAddon3:false,packageWeight:weight,itemCount:items },detailed.total);
  const rows=[...detailed.lineItems,...rules.lineItems];
  return <div className="mx-auto max-w-5xl space-y-6 p-4 lg:p-10"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-red-600">Phase 33</p><h1 className="mt-1 text-3xl font-black text-slate-950 dark:text-white">Pricing Simulator</h1><p className="mt-2 text-sm font-medium text-slate-500">Test your current live pricing profile and Phase 35 rules without creating a customer quote.</p></div><form className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-[#111] sm:grid-cols-4"><label className="text-xs font-black text-slate-500">Miles<input name="distance" type="number" step="0.1" defaultValue={distance} className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/></label><label className="text-xs font-black text-slate-500">Weight lbs<input name="weight" type="number" step="1" defaultValue={weight} className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/></label><label className="text-xs font-black text-slate-500">Items<input name="items" type="number" defaultValue={items} className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/></label><label className="text-xs font-black text-slate-500">Stair flights<input name="stairs" type="number" defaultValue={stairs} className="mt-2 w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm"/></label><button className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-black text-white sm:col-span-4">Run simulation</button></form><div className="rounded-3xl bg-slate-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-wider text-white/50">Simulated total</div><div className="mt-2 text-4xl font-black">${rules.total.toFixed(2)}</div><div className="mt-5 divide-y divide-white/10">{rows.map((r)=><div key={r.key} className="flex justify-between py-3 text-sm"><span className="font-bold text-white/75">{r.label}</span><span className="font-black">${r.amount.toFixed(2)}</span></div>)}</div></div><div className="flex gap-4 text-sm font-black text-red-600"><Link href="/dashboard/pricing/templates">Pricing templates →</Link><Link href="/dashboard/pricing/rules">Rules engine →</Link></div></div>;
}
