"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { useTheme } from "next-themes";

interface DailyQuoteData {
  date: string;
  count: number;
}

interface QuoteTrendChartProps {
  data: DailyQuoteData[];
}

export default function QuoteTrendChart({ data }: QuoteTrendChartProps) {
  const { resolvedTheme } = useTheme();
  const isDark = resolvedTheme === "dark";

  return (
    <div className="bg-white dark:bg-[#1e1e1e] p-6 rounded-none border border-slate-200/60 dark:border-white/[0.06] shadow-sm dark:shadow-none flex flex-col h-full">
      <div className="mb-6">
        <h3 className="text-lg font-black text-slate-900 dark:text-slate-100 tracking-tight">
          Quote Requests (Last 7 Days)
        </h3>
        <p className="text-xs text-slate-500 dark:text-slate-400 font-medium">Daily quote volume generated by your widget</p>
      </div>
      
      <div className="flex-1 min-h-[240px] w-full">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart
            data={data}
            margin={{ top: 10, right: 10, left: -20, bottom: 0 }}
          >
            <CartesianGrid strokeDasharray="3 3" vertical={false} stroke={isDark ? "rgba(255,255,255,0.04)" : "#f1f5f9"} />
            <XAxis
              dataKey="date"
              axisLine={false}
              tickLine={false}
              tick={{ fontSize: 12, fill: isDark ? "#94a3b8" : "#64748b", fontWeight: 500 }}
              dy={10}
            />
            <YAxis
              axisLine={false}
              tickLine={false}
              tick={{ fontSize: 12, fill: isDark ? "#94a3b8" : "#64748b", fontWeight: 500 }}
              allowDecimals={false}
            />
            <Tooltip
              cursor={{ fill: isDark ? "rgba(255,255,255,0.03)" : "#f8fafc" }}
              contentStyle={{
                backgroundColor: isDark ? "#252526" : "#ffffff",
                borderRadius: "12px",
                border: isDark ? "1px solid rgba(255,255,255,0.08)" : "1px solid #e2e8f0",
                boxShadow: isDark ? "0 10px 15px -3px rgba(0,0,0,0.4)" : "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
                padding: "8px 12px",
                color: isDark ? "#e2e8f0" : undefined,
              }}
              labelStyle={{ color: isDark ? "#94a3b8" : "#64748b", fontWeight: 600, fontSize: "12px", marginBottom: "4px" }}
              itemStyle={{ color: "#e9001a", fontWeight: 800, fontSize: "14px", padding: 0 }}
            />
            <Bar
              dataKey="count"
              name="Quotes"
              fill="#e9001a"
              radius={[0, 0, 0, 0]}
              maxBarSize={48}
              animationDuration={1500}
            />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
